CREATE TABLE IF NOT EXISTS drinks (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  price REAL
);

INSERT INTO drinks (id, name, price) VALUES (1, 'Tusker Lager', 250);
INSERT INTO drinks (id, name, price) VALUES (2, 'Tusker Cider', 300);
INSERT INTO drinks (id, name, price) VALUES (3, 'Tusker litre', 250);
INSERT INTO drinks (id, name, price) VALUES (4, 'Tusker Ndimu', 230);
INSERT INTO drinks (id, name, price) VALUES (5, 'Manyatta', 300);
INSERT INTO drinks (id, name, price) VALUES (6, 'Snap Cider', 300);
INSERT INTO drinks (id, name, price) VALUES (7, 'Pilsner', 250);
INSERT INTO drinks (id, name, price) VALUES (8, 'Malts', 250);
INSERT INTO drinks (id, name, price) VALUES (9, 'White Cap', 300);
INSERT INTO drinks (id, name, price) VALUES (10, 'White Cap Light', 300);
INSERT INTO drinks (id, name, price) VALUES (11, 'G.K', 300);
INSERT INTO drinks (id, name, price) VALUES (12, 'Guinness 300ml', 230);
INSERT INTO drinks (id, name, price) VALUES (13, 'Smirnoff Black Ice', 300);
INSERT INTO drinks (id, name, price) VALUES (14, 'Punch Beer', 300);
INSERT INTO drinks (id, name, price) VALUES (15, 'Snapp', 300);
INSERT INTO drinks (id, name, price) VALUES (16, 'Balozi', 250);
INSERT INTO drinks (id, name, price) VALUES (17, 'Guinness Smooth', 230);
INSERT INTO drinks (id, name, price) VALUES (18, 'Smirnoff Ice Can', 300);
INSERT INTO drinks (id, name, price) VALUES (19, 'Punch Can', 300);
INSERT INTO drinks (id, name, price) VALUES (20, 'Savannah Lemon', 350);
INSERT INTO drinks (id, name, price) VALUES (21, 'Tusker lite can', 350);
INSERT INTO drinks (id, name, price) VALUES (22, 'Pilsner can', 300);
INSERT INTO drinks (id, name, price) VALUES (23, 'W/cap can', 350);
INSERT INTO drinks (id, name, price) VALUES (24, 'Malt can', 350);
INSERT INTO drinks (id, name, price) VALUES (25, 'Tusker can', 300);
INSERT INTO drinks (id, name, price) VALUES (26, 'Tusker Cider can', 350);
INSERT INTO drinks (id, name, price) VALUES (27, 'Snapp can', 300);
INSERT INTO drinks (id, name, price) VALUES (28, 'G.K can', 350);
INSERT INTO drinks (id, name, price) VALUES (29, 'Balozi can', 300);
INSERT INTO drinks (id, name, price) VALUES (30, 'Gordon tonic purple', 300);
INSERT INTO drinks (id, name, price) VALUES (31, 'Gordon Tonic Pink', 300);
INSERT INTO drinks (id, name, price) VALUES (32, 'Faxe can', 350);
INSERT INTO drinks (id, name, price) VALUES (33, 'Guarana', 300);
INSERT INTO drinks (id, name, price) VALUES (34, 'Heineken', 350);
INSERT INTO drinks (id, name, price) VALUES (35, 'Heineken can', 400);
INSERT INTO drinks (id, name, price) VALUES (36, 'Heineken zero', 300);
INSERT INTO drinks (id, name, price) VALUES (37, 'Ko', 300);
INSERT INTO drinks (id, name, price) VALUES (38, 'Summit', 250);
INSERT INTO drinks (id, name, price) VALUES (39, 'Desperado', 330);
INSERT INTO drinks (id, name, price) VALUES (40, 'Hunters Cider Gold', 300);
INSERT INTO drinks (id, name, price) VALUES (41, 'Hunters Cider dry', 300);
INSERT INTO drinks (id, name, price) VALUES (42, 'Savanna', 350);
INSERT INTO drinks (id, name, price) VALUES (43, 'Red bull', 300);
INSERT INTO drinks (id, name, price) VALUES (44, 'Kingfisher', 300);
INSERT INTO drinks (id, name, price) VALUES (45, 'Fanta Orange', 100);
INSERT INTO drinks (id, name, price) VALUES (46, 'Fanta Passion', 100);
INSERT INTO drinks (id, name, price) VALUES (47, 'Fanta Black Current', 100);
INSERT INTO drinks (id, name, price) VALUES (48, 'Sprite', 100);
INSERT INTO drinks (id, name, price) VALUES (49, 'Krest', 100);
INSERT INTO drinks (id, name, price) VALUES (50, 'Stoney', 100);
INSERT INTO drinks (id, name, price) VALUES (51, 'Coke', 100);
INSERT INTO drinks (id, name, price) VALUES (52, 'Soda water', 120);
INSERT INTO drinks (id, name, price) VALUES (53, 'Tonic', 120);
INSERT INTO drinks (id, name, price) VALUES (54, 'Minute maid apple', 250);
INSERT INTO drinks (id, name, price) VALUES (55, 'Minute maid mango', 250);
INSERT INTO drinks (id, name, price) VALUES (56, 'Minute maid tropical', 250);
INSERT INTO drinks (id, name, price) VALUES (57, 'Alvaro', 150);
INSERT INTO drinks (id, name, price) VALUES (58, 'Monster black', 300);
INSERT INTO drinks (id, name, price) VALUES (59, 'Monster yellow', 300);
INSERT INTO drinks (id, name, price) VALUES (60, 'Monster White', 300);
INSERT INTO drinks (id, name, price) VALUES (61, 'Monster Blue', 300);
INSERT INTO drinks (id, name, price) VALUES (62, 'Coke zero', 150);
INSERT INTO drinks (id, name, price) VALUES (63, 'Tonic Plastic', 150);
INSERT INTO drinks (id, name, price) VALUES (64, 'Lemonade', 100);
INSERT INTO drinks (id, name, price) VALUES (65, 'Novida', 120);
INSERT INTO drinks (id, name, price) VALUES (66, 'Del Pure Apple', 400);
INSERT INTO drinks (id, name, price) VALUES (67, 'Blend Mango', 400);
INSERT INTO drinks (id, name, price) VALUES (68, 'Blend Tropical', 400);
INSERT INTO drinks (id, name, price) VALUES (69, 'Blend Mixed Berry', 400);
INSERT INTO drinks (id, name, price) VALUES (70, 'Blend Orange', 400);
INSERT INTO drinks (id, name, price) VALUES (71, 'Blend Mango/Pineapple', 400);
INSERT INTO drinks (id, name, price) VALUES (72, 'Blend Passion', 400);
INSERT INTO drinks (id, name, price) VALUES (73, 'Pick and peel', 400);
INSERT INTO drinks (id, name, price) VALUES (74, 'Water 1 Litre Dasani', 150);
INSERT INTO drinks (id, name, price) VALUES (75, 'Water 1 Litre Kiringet', 200);
INSERT INTO drinks (id, name, price) VALUES (76, 'Water 1 Litre Aqua', 150);
INSERT INTO drinks (id, name, price) VALUES (77, 'Water 1/2 Litre Dasani', 80);
INSERT INTO drinks (id, name, price) VALUES (78, 'Water 1/2 Litre Aqua', 80);
INSERT INTO drinks (id, name, price) VALUES (79, '750ml 4ths Red', 1500);
INSERT INTO drinks (id, name, price) VALUES (80, '750ml 4ths White', 1500);
INSERT INTO drinks (id, name, price) VALUES (81, '4 Cousins Red', 1500);
INSERT INTO drinks (id, name, price) VALUES (82, '4 Cousins White', 1500);
INSERT INTO drinks (id, name, price) VALUES (83, 'St Mary', 1500);
INSERT INTO drinks (id, name, price) VALUES (84, '51 4th Street Red', 300);
INSERT INTO drinks (id, name, price) VALUES (85, '4th Street White', 300);
INSERT INTO drinks (id, name, price) VALUES (86, 'C. Sweet Red', 300);
INSERT INTO drinks (id, name, price) VALUES (87, 'C. White Sweet', 300);
INSERT INTO drinks (id, name, price) VALUES (88, 'Red dry drosdy hof', 300);
INSERT INTO drinks (id, name, price) VALUES (89, 'C. white dry drotsy hof', 300);
INSERT INTO drinks (id, name, price) VALUES (90, 'Caprice red dry', 1200);
INSERT INTO drinks (id, name, price) VALUES (91, 'Caprice white dry', 1200);
INSERT INTO drinks (id, name, price) VALUES (92, 'Caprice sweet red', 1200);
INSERT INTO drinks (id, name, price) VALUES (93, 'Wine Casabuena White', 1000);
INSERT INTO drinks (id, name, price) VALUES (94, 'Wine Casabuena Red', 1000);
INSERT INTO drinks (id, name, price) VALUES (95, 'Cell white 51..', 6000);
INSERT INTO drinks (id, name, price) VALUES (96, 'C, Morgans 1/4', 600);
INSERT INTO drinks (id, name, price) VALUES (97, 'Hunters 1/2', 700);
INSERT INTO drinks (id, name, price) VALUES (98, '1/4 Viceroy', 700);
INSERT INTO drinks (id, name, price) VALUES (99, '1/2 Viceroy', 1000);
INSERT INTO drinks (id, name, price) VALUES (100, '1/4 Richot', 700);
INSERT INTO drinks (id, name, price) VALUES (101, '1/2 Richot', 1000);
INSERT INTO drinks (id, name, price) VALUES (102, '1/4 K.cane', 500);
INSERT INTO drinks (id, name, price) VALUES (103, '1/2 K.C', 700);
INSERT INTO drinks (id, name, price) VALUES (104, '1/4 S.vodka', 700);
INSERT INTO drinks (id, name, price) VALUES (105, '1/2 S. vodka', 1000);
INSERT INTO drinks (id, name, price) VALUES (106, '1/2 Vat69', 1200);
INSERT INTO drinks (id, name, price) VALUES (107, '1/4 Bond 7', 700);
INSERT INTO drinks (id, name, price) VALUES (108, '1/2 Bond', 1000);
INSERT INTO drinks (id, name, price) VALUES (109, '1/4 Gilbeys', 700);
INSERT INTO drinks (id, name, price) VALUES (110, '1/2 Gilbeys', 1000);
INSERT INTO drinks (id, name, price) VALUES (111, 'Black & w 750', 2500);
INSERT INTO drinks (id, name, price) VALUES (112, 'Black & W 1/2', 1000);
INSERT INTO drinks (id, name, price) VALUES (113, 'Black & White 1Ltr', 3000);
INSERT INTO drinks (id, name, price) VALUES (114, 'Tangaline 10 Litre', 6500);
INSERT INTO drinks (id, name, price) VALUES (115, 'Tangaline 750 ml', 3500);
INSERT INTO drinks (id, name, price) VALUES (116, '1/2 Jack Daniel', 2800);
INSERT INTO drinks (id, name, price) VALUES (117, '1/2 Famous', 1800);
INSERT INTO drinks (id, name, price) VALUES (118, 'Best Gin 1/4', 600);
INSERT INTO drinks (id, name, price) VALUES (119, 'Best Gin', 1500);
INSERT INTO drinks (id, name, price) VALUES (120, '1/2 J.B', 1800);
INSERT INTO drinks (id, name, price) VALUES (121, '1/4 Johnnie Red', 1200);
INSERT INTO drinks (id, name, price) VALUES (122, '1/4 Johnnie Black', 1500);
INSERT INTO drinks (id, name, price) VALUES (123, 'Best whiskey 1/4', 600);
INSERT INTO drinks (id, name, price) VALUES (124, '750 Best Whiskey', 1500);
INSERT INTO drinks (id, name, price) VALUES (125, 'Best Vodka', 1500);
INSERT INTO drinks (id, name, price) VALUES (126, 'Malibu', 200);
INSERT INTO drinks (id, name, price) VALUES (127, '7.5 Viceroy', 150);
INSERT INTO drinks (id, name, price) VALUES (128, '7.5 Richot', 150);
INSERT INTO drinks (id, name, price) VALUES (129, '7.5 S. Vodka', 150);
INSERT INTO drinks (id, name, price) VALUES (130, '7.5 Vat 69', 150);
INSERT INTO drinks (id, name, price) VALUES (131, '7.5 Gilbeys', 150);
INSERT INTO drinks (id, name, price) VALUES (132, '7.5 Amarula', 200);
INSERT INTO drinks (id, name, price) VALUES (133, '7.5 Zappa Rd', 150);
INSERT INTO drinks (id, name, price) VALUES (134, 'Tequila Rose', 200);
INSERT INTO drinks (id, name, price) VALUES (135, 'Myus Tot', 200);
INSERT INTO drinks (id, name, price) VALUES (136, 'J.M Black', 250);
INSERT INTO drinks (id, name, price) VALUES (137, 'J.M Red Ibl', 200);
INSERT INTO drinks (id, name, price) VALUES (138, 'Camino clear', 250);
INSERT INTO drinks (id, name, price) VALUES (139, 'Jameson', 200);
INSERT INTO drinks (id, name, price) VALUES (140, 'Jack Daniel', 250);
INSERT INTO drinks (id, name, price) VALUES (141, 'South comfort', 200);
INSERT INTO drinks (id, name, price) VALUES (142, 'Lime', 20);
INSERT INTO drinks (id, name, price) VALUES (143, 'Embassy', 27.5);
INSERT INTO drinks (id, name, price) VALUES (144, 'S.M', 22.5);
INSERT INTO drinks (id, name, price) VALUES (145, 'Sportman', 22.5);
INSERT INTO drinks (id, name, price) VALUES (146, 'Dunhill', 22.5);
INSERT INTO drinks (id, name, price) VALUES (147, 'All Seasons', 1800);
INSERT INTO drinks (id, name, price) VALUES (148, 'Honey', 50);
INSERT INTO drinks (id, name, price) VALUES (149, 'Hedex', 20);
INSERT INTO drinks (id, name, price) VALUES (150, 'Panadol', 20);
INSERT INTO drinks (id, name, price) VALUES (151, 'Actal', 20);
INSERT INTO drinks (id, name, price) VALUES (152, 'Mara moja', 20);
INSERT INTO drinks (id, name, price) VALUES (153, 'Salama', 150);
INSERT INTO drinks (id, name, price) VALUES (154, 'Kiss', 150);
INSERT INTO drinks (id, name, price) VALUES (155, 'Cap.mor spiced tot', 150);
INSERT INTO drinks (id, name, price) VALUES (156, 'Durex', 150);
INSERT INTO drinks (id, name, price) VALUES (157, 'Captain Gold', 2000);
INSERT INTO drinks (id, name, price) VALUES (158, 'Captains', 2500);
INSERT INTO drinks (id, name, price) VALUES (159, 'Cap Morgan Black & Spe', 3000);
INSERT INTO drinks (id, name, price) VALUES (160, 'Kibao', 1400);
INSERT INTO drinks (id, name, price) VALUES (161, 'Viceroy', 2500);
INSERT INTO drinks (id, name, price) VALUES (162, 'Grants 1/2', 1800);
INSERT INTO drinks (id, name, price) VALUES (163, 'Grants 750', 2800);
INSERT INTO drinks (id, name, price) VALUES (164, 'Richot', 2500);
INSERT INTO drinks (id, name, price) VALUES (165, 'Gilbeys', 2500);
INSERT INTO drinks (id, name, price) VALUES (166, 'Gentleman jack', 6500);
INSERT INTO drinks (id, name, price) VALUES (167, 'S.Red', 2500);
INSERT INTO drinks (id, name, price) VALUES (168, 'S.Orange', 2000);
INSERT INTO drinks (id, name, price) VALUES (169, 'Jagermeister 11', 5000);
INSERT INTO drinks (id, name, price) VALUES (170, 'Jagermeister', 4000);
INSERT INTO drinks (id, name, price) VALUES (171, 'Bond 7', 2500);
INSERT INTO drinks (id, name, price) VALUES (172, 'Baron', 1500);
INSERT INTO drinks (id, name, price) VALUES (173, 'VAT 69', 2500);
INSERT INTO drinks (id, name, price) VALUES (174, 'JW Black 750ml', 5500);
INSERT INTO drinks (id, name, price) VALUES (175, 'JW Black 1 Litre', 6500);
INSERT INTO drinks (id, name, price) VALUES (176, 'John black 1/2', 2850);
INSERT INTO drinks (id, name, price) VALUES (177, 'JW Red 750ml', 3000);
INSERT INTO drinks (id, name, price) VALUES (178, '1Ltr JW Red', 3500);
INSERT INTO drinks (id, name, price) VALUES (179, 'Joh Wal Red 1/2', 1800);
INSERT INTO drinks (id, name, price) VALUES (180, '1 Litre Baileys', 3500);
INSERT INTO drinks (id, name, price) VALUES (181, 'Baileys', 3500);
INSERT INTO drinks (id, name, price) VALUES (182, 'Baileys 375', 1800);
INSERT INTO drinks (id, name, price) VALUES (183, 'Amalura', 3500);
INSERT INTO drinks (id, name, price) VALUES (184, '1/2 Amalura', 1800);
INSERT INTO drinks (id, name, price) VALUES (185, 'Hunters', 1500);
INSERT INTO drinks (id, name, price) VALUES (186, 'Jack Daniel', 5000);
INSERT INTO drinks (id, name, price) VALUES (187, 'Lime', 200);
INSERT INTO drinks (id, name, price) VALUES (188, 'J&B', 3000);
INSERT INTO drinks (id, name, price) VALUES (189, 'J.D 1Ltr', 6000);
INSERT INTO drinks (id, name, price) VALUES (190, 'Cellar white', 1700);
INSERT INTO drinks (id, name, price) VALUES (191, 'Cellar red', 1700);
INSERT INTO drinks (id, name, price) VALUES (192, 'Jameson 1L', 4500);
INSERT INTO drinks (id, name, price) VALUES (193, 'Jameson', 3500);
INSERT INTO drinks (id, name, price) VALUES (194, 'James 1/2', 2000);
INSERT INTO drinks (id, name, price) VALUES (195, 'K.Cane', 1500);
INSERT INTO drinks (id, name, price) VALUES (196, 'Famous', 3500);
INSERT INTO drinks (id, name, price) VALUES (197, 'Famous 1 litre', 4200);
INSERT INTO drinks (id, name, price) VALUES (198, 'Malibu', 3000);
INSERT INTO drinks (id, name, price) VALUES (199, 'S.Comfort', 3500);
INSERT INTO drinks (id, name, price) VALUES (200, '1/2 Gordons', 1300);
INSERT INTO drinks (id, name, price) VALUES (201, 'Gordon pink', 3000);
INSERT INTO drinks (id, name, price) VALUES (202, 'Gordon 750 ml', 3000);
INSERT INTO drinks (id, name, price) VALUES (203, 'Gordon 1 Litre', 3500);
INSERT INTO drinks (id, name, price) VALUES (204, 'Gordon Cicilian', 3000);
INSERT INTO drinks (id, name, price) VALUES (205, 'Camino Clear', 3500);
INSERT INTO drinks (id, name, price) VALUES (206, 'Lime 1.5L', 400);
INSERT INTO drinks (id, name, price) VALUES (207, 'Martini Rosso', 3000);
INSERT INTO drinks (id, name, price) VALUES (208, 'Jack Daniel Honey 750ml', 6500);
INSERT INTO drinks (id, name, price) VALUES (209, 'South comfort 1/2', 1800);
INSERT INTO drinks (id, name, price) VALUES (210, 'Martel VSOP 700ml', 10500);
INSERT INTO drinks (id, name, price) VALUES (211, 'Remmy Martin 1L', 9000);
INSERT INTO drinks (id, name, price) VALUES (212, 'Hennesy', 8500);
INSERT INTO drinks (id, name, price) VALUES (213, 'Hennesy', 13000);
INSERT INTO drinks (id, name, price) VALUES (214, 'Hennesy Very Special', 13500);
INSERT INTO drinks (id, name, price) VALUES (215, 'Hennesy VSOP 1L', 15500);
INSERT INTO drinks (id, name, price) VALUES (216, 'Hennesy VSOP 750ml', 14500);
INSERT INTO drinks (id, name, price) VALUES (217, 'Famous Smokie', 3500);
INSERT INTO drinks (id, name, price) VALUES (218, 'Robertson Red', 1800);
INSERT INTO drinks (id, name, price) VALUES (219, 'Robertson White', 1800);
INSERT INTO drinks (id, name, price) VALUES (220, 'Germister Tort', 250);
INSERT INTO drinks (id, name, price) VALUES (221, 'Singleton 15 years', 8500);
INSERT INTO drinks (id, name, price) VALUES (222, 'Single ton 12 years', 6000);
INSERT INTO drinks (id, name, price) VALUES (223, 'Ballantine 750ml', 3500);
INSERT INTO drinks (id, name, price) VALUES (224, 'Ballantine 11', 4200);
INSERT INTO drinks (id, name, price) VALUES (225, 'William Lawson 750', 2800);
INSERT INTO drinks (id, name, price) VALUES (226, 'William Lawson 350', 1500);
INSERT INTO drinks (id, name, price) VALUES (227, 'Wiliam 1L', 3800);
INSERT INTO drinks (id, name, price) VALUES (228, 'Drosdy Hof Red', 1700);
INSERT INTO drinks (id, name, price) VALUES (229, 'Drosdy Hof White', 1700);
INSERT INTO drinks (id, name, price) VALUES (230, 'Jw gold reserve', 8000);
INSERT INTO drinks (id, name, price) VALUES (231, 'Tangaline Gin 750ml', 3500);
INSERT INTO drinks (id, name, price) VALUES (232, 'Tanguery De Savilla', 3500);
INSERT INTO drinks (id, name, price) VALUES (233, 'Tanguery Rangpur', 3500);
INSERT INTO drinks (id, name, price) VALUES (234, 'Tanguery Royale', 3500);
INSERT INTO drinks (id, name, price) VALUES (235, 'Jw Double Black 750', 8500);
INSERT INTO drinks (id, name, price) VALUES (236, 'Jw Double Black 1L', 10000);
INSERT INTO drinks (id, name, price) VALUES (237, 'Jack D Honey 1', 9000);
INSERT INTO drinks (id, name, price) VALUES (238, 'John Barr Red', 2500);
INSERT INTO drinks (id, name, price) VALUES (239, 'Absolute Vodka', 3000);
INSERT INTO drinks (id, name, price) VALUES (240, 'Glenfiddish', 15000);
INSERT INTO drinks (id, name, price) VALUES (241, 'Martel VSOP 1L', 15000);
INSERT INTO drinks (id, name, price) VALUES (242, 'St Remy XO', 3000);
INSERT INTO drinks (id, name, price) VALUES (243, 'St remy VSOP 1L', 3500);
INSERT INTO drinks (id, name, price) VALUES (244, 'Myers rum', 3000);
INSERT INTO drinks (id, name, price) VALUES (245, 'KO Classic', 3800);
INSERT INTO drinks (id, name, price) VALUES (246, 'Best Vodka 1/4', 550);
INSERT INTO drinks (id, name, price) VALUES (247, 'Stolichanya', 3000);
INSERT INTO drinks (id, name, price) VALUES (248, 'Southern Comfort 1L', 4200);
INSERT INTO drinks (id, name, price) VALUES (249, 'V&A 1/4', 550);
INSERT INTO drinks (id, name, price) VALUES (250, 'V&A 3/4', 1400);
INSERT INTO drinks (id, name, price) VALUES (251, 'Talister', 8500);
INSERT INTO drinks (id, name, price) VALUES (252, 'Sheridan', 6500);
INSERT INTO drinks (id, name, price) VALUES (253, 'Chrome 750ml', 1200);
INSERT INTO drinks (id, name, price) VALUES (254, 'Rangol 1/2', 80);
INSERT INTO drinks (id, name, price) VALUES (255, 'Rangol 1 Litre', 150);
INSERT INTO drinks (id, name, price) VALUES (256, 'Pineapple', 400);
INSERT INTO drinks (id, name, price) VALUES (257, 'Predator', 120);
INSERT INTO drinks (id, name, price) VALUES (258, 'Summit Malt', 250);
INSERT INTO drinks (id, name, price) VALUES (259, 'Martel VS', 7000);
INSERT INTO drinks (id, name, price) VALUES (260, 'Rosso Nobble', 2500);
INSERT INTO drinks (id, name, price) VALUES (261, 'J&B 1 Litre', 4000);
INSERT INTO drinks (id, name, price) VALUES (262, 'Black Bird', 1500);
INSERT INTO drinks (id, name, price) VALUES (263, 'Grants 1 Litre', 3800);
INSERT INTO drinks (id, name, price) VALUES (264, 'J. Quovo', 3500);
INSERT INTO drinks (id, name, price) VALUES (265, 'Casemigos', 7500);
INSERT INTO drinks (id, name, price) VALUES (266, 'Windhoek', 250);
INSERT INTO drinks (id, name, price) VALUES (267, 'Curiong Can', 350);
INSERT INTO drinks (id, name, price) VALUES (268, 'Manyatta Can', 350);
INSERT INTO drinks (id, name, price) VALUES (269, '750ml 58 Gin', 2000);
INSERT INTO drinks (id, name, price) VALUES (270, '58 Gin Can', 300);
INSERT INTO drinks (id, name, price) VALUES (271, 'Bacardi 1 Litre', 3800);
INSERT INTO drinks (id, name, price) VALUES (272, 'Bacardi 750ml', 3000);
INSERT INTO drinks (id, name, price) VALUES (273, 'John Bar Black', 3000);
INSERT INTO drinks (id, name, price) VALUES (274, 'Jack Daniel Legacy', 4000);
INSERT INTO drinks (id, name, price) VALUES (275, 'Bombay 1 Litre', 4200);
INSERT INTO drinks (id, name, price) VALUES (276, 'Bombay 750ml', 3500);
INSERT INTO drinks (id, name, price) VALUES (277, 'Cran berry', 400);
INSERT INTO drinks (id, name, price) VALUES (278, 'Hampton', 2500);
INSERT INTO drinks (id, name, price) VALUES (279, 'Flirt vodka 750ml', 3000);
INSERT INTO drinks (id, name, price) VALUES (280, 'Tanguiry 1 Litre', 4800);
INSERT INTO drinks (id, name, price) VALUES (281, '1/2 58 Gin', 1000);
INSERT INTO drinks (id, name, price) VALUES (282, 'Chivas 750ml', 5800);
INSERT INTO drinks (id, name, price) VALUES (283, 'Grants 12Yrs', 4500);
INSERT INTO drinks (id, name, price) VALUES (284, 'J.W Blonde', 3500);
INSERT INTO drinks (id, name, price) VALUES (285, 'John Barr Black 1L', 3800);
INSERT INTO drinks (id, name, price) VALUES (286, 'Martel VS 1L', 10500);
INSERT INTO drinks (id, name, price) VALUES (287, 'Don Julio', 11000);
INSERT INTO drinks (id, name, price) VALUES (288, 'Crips Can', 350);
INSERT INTO drinks (id, name, price) VALUES (289, 'KO Can', 300);
INSERT INTO drinks (id, name, price) VALUES (290, 'KO Dry', 250);
INSERT INTO drinks (id, name, price) VALUES (291, '750 Vintage', 1500);
INSERT INTO drinks (id, name, price) VALUES (292, '750 Kikao', 1500);
INSERT INTO drinks (id, name, price) VALUES (293, '1/4 Kikao', 500);
INSERT INTO drinks (id, name, price) VALUES (294, '1/2 Kikao', 1000);
INSERT INTO drinks (id, name, price) VALUES (295, '1/4 Vintage', 500);
INSERT INTO drinks (id, name, price) VALUES (296, '1/2 Vintage', 1000);
INSERT INTO drinks (id, name, price) VALUES (297, 'Asconi', 2800);
INSERT INTO drinks (id, name, price) VALUES (298, 'VB', 230);
INSERT INTO drinks (id, name, price) VALUES (299, 'Roe & Co', 6000);
INSERT INTO drinks (id, name, price) VALUES (300, 'Best Cream', 2000);
INSERT INTO drinks (id, name, price) VALUES (301, 'Tuborg', 330);
INSERT INTO drinks (id, name, price) VALUES (302, 'Jinro', 450);
INSERT INTO drinks (id, name, price) VALUES (303, 'ZMR', 2500);
INSERT INTO drinks (id, name, price) VALUES (304, 'Match Box', NULL);
INSERT INTO drinks (id, name, price) VALUES (305, 'Blue Curacao', NULL);
INSERT INTO drinks (id, name, price) VALUES (306, 'Triple Sec', NULL);
INSERT INTO drinks (id, name, price) VALUES (307, 'Brothers', NULL);
INSERT INTO drinks (id, name, price) VALUES (308, 'Soda 1.5 Litres', NULL);
INSERT INTO drinks (id, name, price) VALUES (309, 'Grenadine', NULL);
