//+------------------------------------------------------------------+
//| ForexSignalEA.mq5 — RSI + MACD + EMA trend-following EA          |
//| Generated by Forex Market Analyzer Bot. Broker: HFM / any MT5.   |
//| Install: MQL5/Experts -> Compile (F4) -> drag onto chart.        |
//| Test on HFM Demo first. Not financial advice.                    |
//+------------------------------------------------------------------+
#property copyright "Forex Analyzer Bot"
#property version   "1.00"
#include <Trade\Trade.mqh>
CTrade trade;

input double InpLot       = 0.10;
input int    InpSLpips    = 30;
input int    InpTPpips    = 60;
input int    InpRSI       = 14;
input int    InpRSIBuy    = 30;
input int    InpRSISell   = 70;
input bool   InpUseMACD   = true;
input bool   InpUseEMA    = true;
input bool   InpNewsBlock = true;

int hRSI, hMACD, hEMA20, hEMA50;

int OnInit()
  {
   hRSI  = iRSI(_Symbol, PERIOD_CURRENT, InpRSI, PRICE_CLOSE);
   hMACD = iMACD(_Symbol, PERIOD_CURRENT, 12, 26, 9, PRICE_CLOSE);
   hEMA20= iMA(_Symbol, PERIOD_CURRENT, 20, 0, MODE_EMA, PRICE_CLOSE);
   hEMA50= iMA(_Symbol, PERIOD_CURRENT, 50, 0, MODE_EMA, PRICE_CLOSE);
   if(hRSI < 0 || hMACD < 0 || hEMA20 < 0 || hEMA50 < 0) return(INIT_FAILED);
   trade.SetExpertMagicNumber(20260924);
   return(INIT_SUCCEEDED);
  }

bool HasPosition()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong t = PositionGetTicket(i);
      if(t > 0 && PositionGetString(POSITION_SYMBOL) == _Symbol) return(true);
     }
   return(false);
  }

double Pip() { return(_Digits == 3 || _Digits == 5 ? _Point * 10 : _Point); }

void OnTick()
  {
   if(HasPosition()) return;
   double r[];
   if(CopyBuffer(hRSI, 0, 1, 1, r) < 1) return;
   double m[], s[];
   if(CopyBuffer(hMACD, 0, 1, 1, m) < 1) return;
   if(CopyBuffer(hMACD, 1, 1, 1, s) < 1) return;
   double e20[], e50[];
   if(CopyBuffer(hEMA20, 0, 1, 1, e20) < 1) return;
   if(CopyBuffer(hEMA50, 0, 1, 1, e50) < 1) return;

   bool bullMACD = m[0] > s[0], bearMACD = m[0] < s[0];
   bool bullEMA  = e20[0] > e50[0], bearEMA = e20[0] < e50[0];

   datetime now = TimeTradeServer();
   if(InpNewsBlock)
     {
      MqlCalendarValue v[];
      int n = CalendarValueHistory(v, now - 7*86400, now + 86400, NULL, NULL);
      for(int i = 0; i < ArraySize(v); i++)
        {
         MqlCalendarEvent ev; MqlCalendarCountry ct;
         if(CalendarEventById(v[i].event_id, ev) && CalendarCountryById(ev.country_id, ct))
           {
            if(ev.importance == CALENDAR_IMPORTANCE_HIGH &&
               (StringFind(ct.code, "US") >= 0 || StringFind(_Symbol, ct.code) >= 0))
              {
               if(MathAbs((long)v[i].time - (long)now) < 15*60) return;
              }
           }
        }
     }

   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double slP = InpSLpips * Pip(), tpP = InpTPpips * Pip();

   bool buyOk  = (r[0] < InpRSIBuy || (r[0] < 50 && bullEMA)) && (!InpUseMACD || bullMACD) && (!InpUseEMA || bullEMA);
   bool sellOk = (r[0] > InpRSISell || (r[0] > 50 && bearEMA)) && (!InpUseMACD || bearMACD) && (!InpUseEMA || bearEMA);

   if(buyOk)
      trade.Buy(InpLot, _Symbol, ask, ask - slP, ask + tpP, "AnalyzerBot BUY RSI " + DoubleToString(r[0], 1));
   else if(sellOk)
      trade.Sell(InpLot, _Symbol, bid, bid + slP, bid - tpP, "AnalyzerBot SELL RSI " + DoubleToString(r[0], 1));
  }
//+------------------------------------------------------------------+
